### ISSUE TITLE
Need help to set up

### ISSUE THREAD

**Issue by JhonnyMnemonic320** [MattMckenzy/Homehook#2]
Hi,

I need help to understand, install and config Homehook.

what I want to achieve is to ask Google Assistant to play some specific artist/song/playlist from a Jellyfin server and have the music start playng on that Google Home device.

I understand that with your code I can ask Google Assistant on one of my Google Home devices to play some specific artist/song/playlist from a Jellyfin server.

I also have a Home Assistant installation (accessible from internet on https with let's encrypt) with Google Assistant configured (in the manual way not the Nabu Casa solution), but I don't understand how **Homehook** interact with **Google Assistant**, **Home Assistant** and the **Jellyfin Server** on my use case scenario.
Do I need Home Assistant only if I want to make some "smart home" automation and is not needed for what I want to achieve?

I have no idea how to run a c+ program in Debian/RapsbianOS or how to run a c program as service. 
Using systemd what do I have to use in at the line `ExecStart =`? If I put the program folder in `/opt` is somenthing like this: `ExecStart = /bin/sh "/opt/Homehook/HomehookService/Startup.cs"`?

Do I have to link Homehook to my google account or it uses Home Assistant component for Google Asssitant?

is better to install Homehook on the same machine of the Jellyfin Server or in the same machine of Home Assistant?

as my primary language is not english/american what I have to change in the configuration to use a different language?

Thanks for your time and for the help.

**Comment by MattMckenzy** [comment]
On the off-chance you're french, I'm french-native so we can chat in that language as well! However, I'll quickly answer your questions in english:


> Do I need Home Assistant only if I want to make some "smart home" automation and is not needed for what I want to achieve?

Basically yes, I just use Home Assistant in my setup to achieve automations with NFC tags and Schedules. To achieve what you're asking (getting google assistant to play Jellyfin media on a Cast device), you only need Jellyfin, Homehook and IFTTT (or Google Actions).


> Using systemd what do I have to use in at the line ExecStart =? If I put the program folder in /opt is somenthing like this: ExecStart = /bin/sh "/opt/Homehook/HomehookService/Startup.cs"?

If you don't want to run Homehook in a docker container (which I recommend), you'll have to make sure you have the dotnet runtime installed. The entrypoint will then be something like 'dotnet "/opt/HomehookService/Homehook.dll"' for the service and  'dotnet "/opt/HomehookApp/Homehook.App.dll"' for the web UI.


> Do I have to link Homehook to my google account or it uses Home Assistant component for Google Asssitant?

Neither! I'm simply using a free IFTTT account to send my voice commands to Homehook through its API. This means however that you'll need to make sure Homehook is externally visible. I expose Homehook through a reverse-proxy server in a Docker container for the added security. The information for Google Account in the configuration is just if you want to support user-specific play sessions in Jellyfin using Google accounts through Google Actions. If you're using IFTTT to trigger Homehook through voice commands, this isn't necessary at all.


> Is better to install Homehook on the same machine of the Jellyfin Server or in the same machine of Home Assistant?

It shouldn't matter where you install Homehook as long as it can communicate with your Jellyfin server through http(s). Make sure you configure the correct address in the Homehook appsettings.json or docker environment variables (i.e. for installation on same machine, it would be http://localhost:8096).


Please let me know if you need more help!

**Comment by JhonnyMnemonic320** [comment]
Thanks for the exaustive ansewer.

I followed your advice: learnt to deal with docker and docker-compose and used the docker images.
So now I have **homehook-service** and **homehook-app** up and running and I can access homehook-app from my LAN on http://192.x.x.x:8125, search for music and let it play on any of my Google Home device.

I also setted up NGINX with a subdomain (and with https) following your README. 
So now the **homehook-service** is exposed to internet (if i understand well protected by the IFTTT:Token and HomehookApp:Token).

I can start music from WAN side using CURL and the IFTTT:Token:
`curl -X POST "https://subdomain.xxx.xxx:port/jelly/simple?apiKey=xxxxxIFTTT:Tokenxxxxx" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"content\":\"random xxxxx songs on xxxxx\"}"`

Now I don't know how to proceed with Google Action. 
I know how to create a project on Google Action and put in on test as  I already made these passages following a guide when I setted up Google Assistant on Home Assistant. But I don't know what I have to do in this case..

Can you please explain and help me to **set up Google Action** so that I can ask Google Asisstant to play some artist/song/playlist on a specific device?

Sorry, I don't speak french. As my primary language is not english/american I was wondering If I have also to change things like preposition from "on/to" or words like "music/artist/play/pause/stop"  to my language. 
In case where I have to change these word? in the `docker-compose.yaml` at the line `Services:Language:WordMappings`?

Thanks
