### ISSUE TITLE
[Question] Play music directly to a google home speaker

### ISSUE THREAD

**Issue by rileygemynd** [MattMckenzy/Homehook#6]
Hi! This looks like a very useful project, great work! I'm surprised there aren't more issues psoted or more contributors. Maybe it works perfectly?

I would like to give this a try, for the main purpose of being able to play jellyfin music directly to a google home speaker (without needing an interface, like on a tv screen or android phone). E.g. Say "play this song on my google speaker" and it will play it. I'm not very familiar with jellyfin though sorry.

Do you know if this is possible? Merci beaucoup!

**Comment by MattMckenzy** [comment]
Yes I use it like this daily! It can even play videos from jellyfin as audio only on speakers. 

Using google voice commands however might be tricky, IFTTT recently changed how they let you use them and I haven't bothered  to try it out.

If you encounter any issues setting it up, please let me know, I'll help as best I can!
