### ISSUE TITLE
Call Next/Previous song from an home-assistant automation

### ISSUE THREAD

**Issue by JhonnyMnemonic320** [MattMckenzy/Homehook#7]
Hi,

I'm using Homehook to cast my music from jellyfin to my GoogleHome speakers.
In the web interface of Homehook is possible to change song to the next/previous. 
It's also possible to tell google assistant to change to the next songs.

However I don't find a way to change to the next song using an Home-Assistant script (I'd like to use an Ikea zigbee remote to controll the music).

While playing media casted using homehook the entity "media_player.my_google_home_speaker" don't accept the service "media_player.media_next_track" or "media_player.media_previous_track".

```
- service: media_player.media_next_track
  data_template:
    entity_id: "media_player.my_google_home_speaker"
```

it seems like Homehook it's not advising HomeAssistant that there are other songs in the play list.

is there any workarround to call the next/previous song from HomeAssistant?

Thanks for your time

**Comment by MattMckenzy** [comment]
There is an API available for homehook as well! I've made the controls available on my stream deck for example. You can have a look at the controller here:  https://github.com/MattMckenzy/Homehook/blob/master/HomehookService/Controllers/JellyController.cs

Here's an example of an API call to skip tracks: https://homehook.mydomain.ca/jelly/MyDeviceName/next?apiKey=11aa22bb334567890abcdef012345

The apiKey would be whatever token you've defined in the appsettings or environment variables, under either IFTTT or HomeAssistant (terrible names, I've never genericized it). 

Let me know if it doesn't work for you and I'll help as best as I can!

**Comment by JhonnyMnemonic320** [comment]
Thanks for the help, It worked. 
I used the url structure you suggested in a rest_command so I can call it from any script/automation in HomeAssistant:
```
rest_command:
  homehook_jelly_next_song:
    url: "https://homehook.mydomain.ca/jelly/MyDeviceName/next?apiKey=11aa22bb334567890abcdef012345"
    method: get
```
